#!/usr/bin/env zsh

() {
	local file
	for file in $(git diff --name-only --staged); do
		[[ -f $file ]] || continue

		local file_ext="${file##*.}"
		if [[ "$file_ext" == "rs" ]]; then
			cargo +nightly fmt --check -- "$file"
		fi
	done

	cargo clippy --all-targets --allow-staged --allow-dirty --color='always'
	cargo test --color='always'
}
